version: '3'

services:
  # 1) sbt
  # .sbt, .ivy2 and .m2 cache directories
  sbt:
    build:
      context: ./
    image: sbt
    container_name: sbt
    volumes:
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
      - ~/.m2:/root/.m2
  # 2) PostgreSQL (Instead of Snowflake)
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5431:5432
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - 18080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
      - ./init-pgadmin/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./init-pgadmin/pgpass:/pgpass # passwords for the connections in this file
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@sample.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
  # 3) Flink
  jobmanager:
    image: flink:latest
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /host/path/to/job/artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2        
  task_manager:
    image: flink:latest
    container_name: task_manager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - /host/path/to/job/artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
volumes:
  volume_postgres:
    name: v_postgres
  volume_pgadmin:
    name: v_pgadmin
